spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false #关闭缓存，及时刷新，上线生产环境需要改为true
    servlet:
      content-type: text/html; charset=utf-8
  mvc:
    static-path-pattern: /static/**



#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml
