server:
  port: 8079
spring:
  datasource:
     url: jdbc:mysql://guoxintongxintongdai.mysql.rds.aliyuncs.com:3999/fqn
     username: x_t_d_g_x_t
     password: wUWKJHHJjhHGdgDGR
     driver-class-name: com.mysql.jdbc.Driver
     # 使用druid数据源
     type: com.alibaba.druid.pool.DruidDataSource

user:
  userName: LiuXiang
  userAge: 19







